language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  - SYMFONY_VERSION="4.4.*"
  - SYMFONY_VERSION="5.1.*"
  - SYMFONY_VERSION="5.2.*"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/framework-bundle:${SYMFONY_VERSION}" --no-update; fi;

install: COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email: eugone.yann@gmail.com
